# Titanic Survival Predictor

```{r, message=FALSE, echo=FALSE}
# Dependencies
dependencies <- c("tidyverse", "ggplot2", "readr", "here", "rsample", "parsnip")
for (pkg in dependencies) {
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg)
  }
  library(pkg, character.only = TRUE)
}
```

```{r}
# Importing the data
path <- here::here("data", "Titanic-Dataset.csv")
data <- read_csv(path)
data
```

## Split Data
```{r}
set.seed(123)
split_data <- initial_split(data, prop = 0.9)

titanic_training <- training(split_data)
titanic_test <- testing(split_data)

glimpse(titanic_test)
glimpse(titanic_training)
```

## Create a linear regression model
```{r}
lr_model <- linear_reg() %>%
  set_engine('lm') %>%
  set_mode('regression')

lr_model

```

## Fit the model to the data
```{r}
lr_fit <- lr_model %>%
  fit(Survived ~ Age + Sex)
```


## Number of NA cabin samples
```{r, echo=FALSE}
total <- length(data$Cabin)
data_no_cabins <- data %>% filter(is.na(Cabin))
wo_cabin <- length(data_no_cabins$Cabin)
sprintf("Total: %s, Without cabins: %s", total, wo_cabin)
glimpse(data_no_cabins)
```

## Plot accuracy
```{r}
```


```{r}
```




